GET http://localhost:3000/groups?page=1&pageSize=10&sortBy=mostLiked&keyword=확인&isPublic=true

###

GET http://localhost:3000/groups

###

GET http://localhost:3000/groups/4

###

GET https://zogakzip4.onrender.com/groups

###

DELETE https://zogakzip4.onrender.com/groups/6
Content-Type: application/json

{
    "password": "2322245"
}

###

GET http://localhost:3000/groups/4
Content-Type: application/json

{
    "password": "1234"
}

###

POST http://localhost:3000/groups
Content-Type: application/json

{
    "name": "스키마 업데이트 테스트",
    "introduction": "스키마",
    "isPublic": false,
    "password": "5678"
}

###

PUT http://localhost:3000/groups/7
Content-Type: application/json

{
    "name": "그룹 수정 여부 확인",
    "introuduction": "PUT2",
    "password": "5678"
}

###

DELETE http://localhost:3000/groups/1
Content-Type: application/json

{
    "password": "12"
}