GET http://localhost:3000/groups

###

GET https://zogakzip4.onrender.com/groups

###

DELETE https://zogakzip4.onrender.com/groups/7
Content-Type: application/json

{
    "password": "2345"
}

###

GET http://localhost:3000/groups/4
Content-Type: application/json

{
    "password": "1234"
}

###

POST http://localhost:3000/groups
Content-Type: application/json

{
    "name": "POST 리퀘스트 테스트092322",
    "description": "POST",
    "public": false,
    "password": "5678"
}

###

PUT http://localhost:3000/groups/10
Content-Type: application/json

{
    "name": "수정 여부 확인",
    "description": "PUT2",
    "password": "2345"
}

###

DELETE http://localhost:3000/groups/10
Content-Type: application/json

{
    "password": "2345"
}