GET http://localhost:3000/groups

###

GET http://localhost:3000/groups/2
Content-Type: application/json

{
    "password": "1234"
}

###

GET http://localhost:3000/posts/1

###

GET https://zogakzip4.onrender.com/groups/posts/2

###

DELETE https://zogakzip4.onrender.com/groups/3
Content-Type: application/json

{
    "password": "2345"
}

###

PUT http://localhost:3000/comments/8
Content-Type: application/json

{
	"nickname": "수정된 댓글 작성자 8",
	"content": "수정된 댓글 내용 8",
	"password": "1234"
}

###

DELETE http://localhost:3000/comments/9
Content-Type: application/json

{
    "password": "1234"
}

###

POST http://localhost:3000/groups/:groupId/posts
Content-Type: application/json

{
    "name": "게시글 작성자 1",
    "title": "게시글 제목 1",
    "name": "게시글 작성자 1",
    "name": "게시글 작성자 1",
    "description": "POST",
    "public": false,
    "password": "5678"
}