GET http://localhost:3000/groups

###

GET https://zogakzip4.onrender.com/groups

###

DELETE https://zogakzip4.onrender.com/groups/6

###

GET http://localhost:3000/groups/5

###

POST http://localhost:3000/groups
Content-Type: application/json

{
    "name": "POST 리퀘스트 테스트",
    "description": "POST",
    "public": false,
    "password": "5678"
}

###

PUT http://localhost:3000/groups/5
Content-Type: application/json

{
    "name": "PUT 리퀘스트 테스트2",
    "description": "PUT2",
    "password": "5678"
}

###

DELETE http://localhost:3000/groups/6
Content-Type: application/json

{
    "password": "2345"
}